update v1.2.5
mxhulab/cryosieve pull request #25
Opened 2024-03-24 05:14 UTC by zerinf

2024-04-04 08:34 UTC, mxhulab commented on README.md
> -This command is specifically for a CUDA environment version 10.2. If your CUDA environment is higher than 10.2, adjust the command based on the suitable variants and versions recommended by the [CuPy
Avoid using "you" or "your" in the text. Instead, opt for the imperative mood.

比如这里，请修改为
Note that this command is tailored for CUDA version 10.2. To accommodate a different CUDA version, adjust the `cudatoolkit` version accordingly. Modify the versions of Python, [CuPy](https://cupy.dev), and [PyTorch](https://pytorch.org) based on requirements, ensuring compatibility with the minimal requirements of CryoSieve.

2024-04-04 08:35 UTC, mxhulab commented on README.md
> +Please note that This command is tailored for CUDA environment version 12.1. For a different CUDA version, you should adjust `pytorch-cuda` version accordingly.
这里建议修改为

Note that this command is tailored for CUDA environment version 12.1. For a different CUDA version, adjust the `pytorch-cuda` version accordingly.

2024-04-04 08:40 UTC, mxhulab requested changes
请稍微修改一下 README。其他没有问题，非常👍。

2024-04-05 14:11 UTC, zerinf commented
这两处已修改。

2024-04-06 03:43 UTC, mxhulab approved these changes

2024-04-06 03:48 UTC, merged